version: "3.6"

services:
    bot:
        image: tgbot:latest
        ports:
          - 80:80
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "docker-echo-bot"
        restart: always
        environment:
            - BOT_TOKEN=1233194283:AAEltBBA7sqZ7HPo5Gxef5fALXiqhyRwBqk
            - POSTGRES_DB=postgres

    postgres:
      image: postgres:latest
      restart: always
      ports:
      - 5432:5432
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres

volumes:
  postgres-db-volume:

