version: "3.6"

volumes:
  postgres-db_volume:

services:
    bot:
        image: tgbot:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "docker-echo-bot"
        restart: always
        environment:
            - BOT_TOKEN=1233194283:AAEltBBA7sqZ7HPo5Gxef5fALXiqhyRwBqk
            - POSTGRES_DB=postgres

    postgres:
      image: postgres:latest
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
